package com.solvd.carinatestautomation.web.warframe.components;

public enum HeaderButton {
    CrossPlatformPlayGuideButton,
    DownloadGameButton,
    ForumsButton,
    GameUpdatesButton,
    HomeButton,
    InitiatePowerPackButton,
    LatestNewsButton,
    LoginButton,
    MarketBundleButton,
    MobileCompanionAppButton,
    NewPlayerGuideButton,
    OfficialDiscordServerButton,
    OfficialMerchButton,
    PlatinumAndBundlesButton,
    PlayFreeNowButton,
    PrimeAccessButton,
    PrimeResurgenceButton,
    QuestGuideButton,
    QuickStartGuideButton,
    RedeemCodeButton,
    ReferralProgramButton,
    ReturningPlayerGuideButton,
    RotatingPageButton,
    StoryRecapButton,
    SupportButton,
    SupporterPacksButton,
    TwitchChannelButton,
    TwitterButton,
    VideosButton,
    WarframeCreatorsButton,
    WarframeVolunteersButton,
    WarframeWikiButton,
    WarframesButton;
}
